import React, { useCallback, useEffect, useState } from 'react'
import Header from './Header'
import Title from '../shared/Title'
import {  Drawer, Grid, Skeleton} from '@mui/material'
import Chatlist from '../specific/Chatlist'
import { samplechats } from '../../constants/sampledata'
import { useNavigate, useParams } from 'react-router-dom'
import Profile from '../specific/Profile'
import { useMyChatsQuery } from '../../redux/api/api'

import { useDispatch, useSelector } from "react-redux";
import { setIsDeleteMenu, setIsMobile, setSelectedDeleteChat } from '../../redux/reducers/misc'
import {useErrors, useSocketEvents} from '../../hooks/hook'
import { getSocket } from '../../socket'
import { NEW_MESSAGE, NEW_MESSAGE_ALERT, NEW_REQUEST, ONLINE_USERS, REFETCH_CHATS } from '../../constants/events'
import { incrementNotification, setNewMessagesAlert } from '../../redux/reducers/chat'
import { getOrSaveFromStorage } from '../../lib/features'
import DeleteChatMenu from '../dialogs/DeleteChatMenu'
import { useRef } from 'react'
// here whatever component is passed here in the wrappedcomponent in that  place i will be pass the   recevied component/props 
// it will directly to the original component
const  Applayout=()=>(WrappedComponent)=> {
  return (props)=>{

    const navigate=useNavigate()
const { isMobile } = useSelector((state) => state.misc);
const { user } = useSelector((state) => state.auth);
const { newMessagesAlert } = useSelector((state) => state.chat);
const deleteMenuAnchor = useRef(null);

const [onlineUsers, setOnlineUsers]= useState([]);
// from here only we send the  onlineuser list to the chatlist to chatitem



  //  from where this "id" will be recevied
  const dispatch = useDispatch();
  // In Redux, the dispatch function is created once when your app starts 
  // (by the Redux store).

  // It stays the same for the entire lifetime of your application.
  
  //  It doesn't get recreated on rerenders.
  //  It doesn't change even if your Redux state changes.





const socket =getSocket();//it will get the socket value
// console.log(socket.id)
  const params = useParams();
  const chatId = params.chatId;//it is for accessing that key-value pair
  // This is a React Router hook that extracts route parameters from the URL.
  // It returns an object containing key-value pairs where the keys are the dynamic segments of the URL.  like chatId
  //  ex
  // <Route path="/chat/:chatId" element={<ChatComponent />} />  if the component is build like this then 
  // And the user visits http://yourwebsite.com/chat/123,
  // then useParams() will return:
  // { chatId: "123" }
  // console.log(chatId)





// Custom hook to fetch chat data using chat/my endpoint
// by default it will provide this many data
// useMyChatsQuery() is auto-generated by RTK Query based on your API slice, and it automatically returns these values:
  const { isLoading, data, isError, error, refetch } = useMyChatsQuery("");
// isLoading true when the request is in progress after fetching the data it will become false
// data	The actual chat data returned by the API if successful
// isError	true if the request failed
// error	Contains error info (like status, message) if isError is true
// refetch	A function you can call to manually re-fetch the data

useErrors([{ isError, error }]);//it will we be called if any  occur this statement will do there work

// console.log(data)


// whenever the page refreshed or component rendering that
// time newMessagesAlert will be changed so it will check the
// local storage any value present for newMessagesAlert
useEffect(() => {
  getOrSaveFromStorage({ key: NEW_MESSAGE_ALERT, value: newMessagesAlert });
}, [newMessagesAlert]);


console.log(   newMessagesAlert
)
// console.log(isMobile)
    const handleMobileClose = () => dispatch(setIsMobile(false));

const handleDeleteChat=(e,chatId,groupChat)=>{
  // e.preventDefault();


  dispatch(setIsDeleteMenu(true));
  dispatch(setSelectedDeleteChat({ chatId, groupChat }));
  // above we will say selected chat is groupchat or not
  deleteMenuAnchor.current = e.currentTarget;
  // console.log("Delete chat",_id,groupchat);
  // alert("jki")
 

}

const newRequestListener = useCallback(() => {
  dispatch(incrementNotification());
}, [dispatch]);
// dispatch:  
  //  It doesn't get recreated on rerenders.
  //  It doesn't change even if your Redux state changes.




const newMessageAlertListener = useCallback(
  (data) => 
    {
// IF THE messages is sent to current chat itself then no need the alert
    if (data.chatId === chatId) return;
    dispatch(setNewMessagesAlert(data));
  },
  [chatId]
);

const refetchListener = useCallback(() => {
  refetch();
  //which means reload the same api call which was triggred earlier  without passing any name just to update the chat cache
  navigate("/");
}, [refetch,
   navigate
  ]);


const onlineUsersListener = useCallback((data) => {
    // FROM HERE WE GET ONLY OTHER MEMBERS ID
    setOnlineUsers(data);
  }, []);

const eventHandlers = {
  [NEW_MESSAGE_ALERT]: newMessageAlertListener,
  [NEW_REQUEST]: newRequestListener,
  [REFETCH_CHATS]: refetchListener,
  [ONLINE_USERS]: onlineUsersListener,
};


useSocketEvents(socket, eventHandlers);

    return (

<>

<Title
 title={"chat app"}  
/>




<DeleteChatMenu
          dispatch={dispatch}
          deleteMenuAnchor={deleteMenuAnchor}
        />

        {isLoading ? (
          <Skeleton />
        ) : (
// if ismobile is true open the drawer otherwise close
// when from the header the user click the drawer it will make the 
// ismobile to true in the   state of the reducer which enables the drawer to open
          <Drawer open={isMobile} onClose={handleMobileClose}>
            <Chatlist
              w="70vw"
              chats={data?.chats}
              chatId={chatId}
              handleDeleteChat={handleDeleteChat}
              newMessagesAlert={newMessagesAlert}
              onlineUsers={onlineUsers}
            />
          </Drawer>
        )}


  <div><Header/></div>
  {/* <WrappedComponent{...props}/> */}
  {/* <div>footer</div> */}



{/* now we are forming 3 Grid2column ->     1| 2   |  3   | like this  */}

{/* 

<Gridcontainer height={"calc(100vh-4rem)"}>
<Griditem
sm={4}
md={3}
sx={{
  display:{xs:"none",sm:"block"}
}}
 height={"100%"} bgcolor={"primary.main"}>
  first
</Griditem>
<Griditem xs={12}  sm={8} md={5} lg={6}height={"100%"} >
<WrappedComponent{...props}/>
</Griditem>

<Griditem md={4} lg={3} 
sx={{
  display:{xs:"none",md:"block"},
  padding:"2rem",
  bgcolor:"rgba(0,0,0,0.85)"
}}
height={"100%"}>
  first
</Griditem>




</Grid2>  */}


<Grid container sx={{ height: "calc(100vh - 4rem)" }}>
  <Grid
    item
    sm={4}
    md={3}
    sx={{
      display: { xs: "none", sm: "block" },
      height: "100vh",  // Ensure full height
      // bgcolor: "primary.main",
      // bgcolor:"rgba(0,0,0,0.85)"

    }}
  >

    {/* from here only we are sending the data to chatlist
     component  which is passed to chatitem component */}

{isLoading ? (
              <Skeleton />
            ) : (
              <Chatlist
                chats={data?.chats}
                // chatId={chatId}
                // handleDeleteChat={handleDeleteChat}
                // newMessagesAlert={newMessagesAlert}
                onlineUsers={onlineUsers}

                // chats={samplechats} 
                // chatId={"1"}
                chatId={chatId}
                handleDeleteChat={handleDeleteChat}
                newMessagesAlert={newMessagesAlert}
                
              />
            )}

{/* <  Chatlist chats={samplechats} 
// chatId={"1"}
chatId={chatId}
handleDeleteChat={handleDeleteChat}
// newMessagesAlert={
//   // chatId
//    [{chatId,//it is accessed usin 
//     count:4}]
  
// }
// onlineUsers={["1","2"]}

/>   */}
</Grid>
  
  <Grid
    item
    xs={12}
    sm={8}
    md={5}
    lg={6}
    sx={{ height: "100%" }} // Ensure it inherits from the container
  >
    <WrappedComponent {...props}  chatId={chatId} user={user} //user came from store
    />
  </Grid>
  
  <Grid
    item
    md={4}
    lg={3}
    sx={{
      display: { xs: "none", md: "block" },
      padding: "2rem",
      bgcolor: "rgba(0,0,0,0.85)",
      height: "100vh", // Ensure full height
    }}
  >
    {/* profile layout */}
    <Profile user={user}/>
  </Grid>
</Grid>





</>

      )
  }
}

export default Applayout;
// now  This function is exported